algoritmo "PARA COM PARA"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : RENAN KIRCHMAIER FAYER
DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

C1,C2: INTEIRO

inicio

    PARA C1 <- 1 ATE 3 PASSO 1 FACA
        PARA C2 <- 1 ATE 3 PASSO 1 FACA
            escreval("C1,C2")
        FIMPARA
    FIMPARA    

fimalgoritmo